const API_ERROR_CODE = {
	ADDRESS_NOT_FOUND_ERROR: 'ADDRESS_NOT_FOUND_ERROR',
	API_FETCH_ERROR: 'API_FETCH_ERROR',
	CLIENT_ERROR: 'CLIENT_ERROR',
	GITHUB_FETCH_ERROR: 'GITHUB_FETCH_ERROR',
	INVALID_PARAMS_ERROR: 'INVALID_PARAMS_ERROR',
	INVALID_SEARCH_PARAMS_ERROR: 'INVALID_SEARCH_PARAMS_ERROR',
	POST_NOT_FOUND_ERROR: 'POST_NOT_FOUND_ERROR',
	REACTION_ACTION_ERROR: 'REACTION_ACTION_ERROR',
	REQ_BODY_ERROR: 'REQ_BODY_ERROR',
	SUBSQUID_FETCH_ERROR: 'SUBSQUID_FETCH_ERROR',
	USER_NOT_FOUND_ERROR: 'USER_NOT_FOUND_ERROR'
};

export default API_ERROR_CODE;
