import type { Metadata } from 'next';
import '@/globals.scss';
import 'react-toastify/dist/ReactToastify.css';

import localFont from '@next/font/local';
import Providers from '@/providers';
import LayoutWrapper from './Components/LayoutWrapper';

const rec = localFont({
	src: './fonts/recharge.otf',
	variable: '--font-rec'
});

const surf = localFont({
	src: './fonts/surfquest.ttf',
	variable: '--font-surf'
});

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'AiGen'
};

export const dynamic = 'force-dynamic';

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`${rec.variable} ${surf.variable} font-manrope`}>
				<Providers>
					<LayoutWrapper>
						{children}
						{/* {modal} */}
					</LayoutWrapper>
				</Providers>
			</body>
		</html>
	);
}
